apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-salom
  labels:
    app: flask-salom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-salom
  template:
    metadata:
      labels:
        app: flask-salom
    spec:
      containers:
      - name: flask-container
        image: docker.io/18c336445927/flask-image:latest # Replace with your actual image
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-demo
spec:
  selector:
    app: flask-salom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer # Use ClusterIP for internal access, LoadBalancer for external access

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # - host: flask-salom.example.com # Replace with your domain
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service-demo
            port:
              number: 80
