
name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: dulcet-radar-402320
  GKE_CLUSTER: 	jx-rocks    # Add your cluster name here.
  GKE_ZONE: us-east1-b   # Add your cluster zone here.
  DEPLOYMENT_NAME: flask-salom # Add your deployment name here.
  IMAGE: flask-image
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
#
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate with Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}
    
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }} # nedir
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    # Get the GKE credentials
    - name: Set up GKE credentials
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.GKE_PROJECT }}

    # Build the Docker image
    - name: Build Docker Image
      run: |-
        docker build \
          --tag "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    - name: Push Docker Image
      run: |-
        docker push "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:$GITHUB_SHA"


    # Push the Docker image to Dockerhub
    - name: Publish
      run: |-
        docker push "docker.io/${{ env.DOCKERHUB_USERNAME }}/$IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        ./kustomize edit set image docker.io/${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
